pipeline {
    agent any

    tools {
        nodejs 'nodejs'  // Ensure this matches the name you set in Jenkins Global Tool Configuration
    }
    
    stages {
        stage('Git Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/Preemashilpa/React-app-to-do-preema.git'
            }
        }
        
        stage('Docker Build and Tag') {
            steps {
                // Update the build context to "Project-30" and specify the Dockerfile path
                sh "docker build -f Project-30/Dockerfile -t preema21/react-to-do-application:1 Project-30"
            }
        }

        stage('Containerization') {
            steps {
                sh '''
                docker stop c1 || true
                docker rm c1 || true
                docker run -it -d --name c1 -p 9000:80 preema21/react-to-do-application:1
                '''
            }
        }
    }
}

